# Using CodeClimate Platform
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

engines:
  eslint:
    enabled: true
  scsslint:
    enabled: true
  watson:
    enabled: true

ratings:
  paths:
  - '**/*.js'
  - '**/*.scss'
